import type { Metadata } from "next";
import { Instrument_Serif, Instrument_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400"

});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: "variable"
});

export const metadata: Metadata = {
  title: "arlinds portfolio",
  keywords: ["portfolio", "arlind", "gurgurovci", "web developer"],
  authors: [{ name: "Arlind Gurgurovci", url: "https://arlind.io" }],
  creator: "Arlind Gurgurovci",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${instrumentSans.variable} antialiased`}
      >
        <div className="flex flex-col items-center justify-center min-h-screen border p-5 gap-32">
                  {children}
                            <Footer />

        </div>

      </body>

    </html>
  );
}
